services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      TYPE: "MODRINTH"
      MODRINTH_MODPACK: "/modpacks/server-pack.mrpack"
      MODRINTH_LOADER: "fabric"
      MODRINTH_DEFAULT_VERSION_TYPE: "release"
      MOTD: "§3Servidor §6casero §3con mods §4Hecho con amor ❤"
      VERSION: "1.20.1"
      MEMORY: "8G"
      MAX_PLAYERS: "5"
      DIFFICULTY: "3"
      LEVEL: "Survival"
      # ONLINE_MODE: "FALSE" Permite jugar pirata
      OVERRIDE_SERVER_PROPERTIES: "true"
    volumes:
      - "minecraft_data:/data"
      - ./modpacks:/modpacks:ro
      - ./config/icon.png:/data/server-icon.png
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    network_mode: "service:minecraft"
    cap_add:
      - NET_ADMIN
    volumes:
      - tailscale_state:/var/lib/tailscale
    environment:
      TS_HOSTNAME: "minecraft-server"
      TS_AUTHKEY: ${TS_AUTHKEY}
    restart: unless-stopped

volumes:
  minecraft_data:
  tailscale_state:
