global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: node_exporter
    static_configs:
      - targets: ['node_exporter:9100']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'node_hwmon_temp_celsius'
        action: keep
      - action: labeldrop
        regex: 'feature|sensor'

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'container_last_seen|container_memory_usage_bytes|container_cpu_user_seconds_total|container_network_receive_bytes_total|container_network_transmit_bytes_total'
        action: keep
      - action: labeldrop
        regex: 'id|container_label_.*|container_env_.*|container_network_.*|container_spec_.*|namespace|pod|container|container_name'