networks:
  monitor-net:
    external: true
    name: monitor-net

services:
  nufi:
    container_name: nufi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
    networks:
      - monitor-net
